<%@ Page Title="Activity Report:." Language="C#" MasterPageFile="~/mInventory/InventoryMaster.master" AutoEventWireup="true" CodeBehind="ActivityReport.aspx.cs" Inherits="MRLWMSC21.mInventory.ActivityReport" %>
<asp:Content ID="BodyContent" ContentPlaceHolderID="InvContent" runat="server">

    <asp:ScriptManager runat="server" ID="ssss" SupportsPartialRendering="true" EnablePartialRendering="true"></asp:ScriptManager> 
    
    <script type="text/javascript" src="Scripts/jquery.blockUI.js"></script>
    <script type="text/javascript" src="Scripts/CommonScripts.js"></script>
   
    <style>
        img
        {  
            border-style: none;
        }
    
        .AutogeneratedNo {
            color:#1a79cf;
            font-weight:bold;
            text-transform:uppercase;
        }


        .innertab div {
            width:100%;
            overflow:auto;
        }

        table, table td{
            white-space:nowrap !important;
        }

        .gvLightSteelBlueNew_DataCellGrid td{
            white-space:nowrap !important;
        }

        .innerScroll ~ div{
            overflow:auto;
        }
    </style>

    <script type="text/javascript">
        $(document).ready(function () {
            
            Sys.WebForms.PageRequestManager.getInstance().add_endRequest(EndRequestHandler);
            function EndRequestHandler(sender, args) {
                if (args.get_error() == undefined) {
                    fnMCodeAC();
                }
            }
            function fnMCodeAC() {
                $(".DateBoxCSS_small").datepicker({ dateFormat: 'dd/mm/yy' });

                var textfieldname = $('#<%=this.txtLocation.ClientID%>');
                DropdownFunction(textfieldname);
                $('#<%=this.txtLocation.ClientID%>').autocomplete({
                    source: function (request, response) {

                        var Damage = document.getElementById('<%=this.chkIsDamag.ClientID%>').checked ? "1" : "0";;
                        var Discrepancy = document.getElementById('<%=this.chkDisc.ClientID%>').checked ? "1" : "0";;

                        if (Damage == 1 || Discrepancy == 1) {
                            
                            $("#<%=hifIsQuarantine.ClientID%>").val("1");
                        }
                        else {
                            $("#<%=hifIsQuarantine.ClientID%>").val("0");
                        }

                        $.ajax({
                            url: '<%=ResolveUrl("~/mWebServices/FalconWebService.asmx/GetLocationListFor3PL") %>',
                            data: "{'Prefix': '" + request.term + "','ProductCategory':'0','InboundID':'" + $("#hifTransactionDocID").val() + "' ,'IsQuarantine':'" + $("#<%=hifIsQuarantine.ClientID %>").val() + "'}",
                        dataType: "json",
                        type: "POST",
                        async: true,
                        contentType: "application/json; charset=utf-8",
                        success: function (data) {
                            response(data.d)
                        }

                    });
                },

                    minLength: 0
                });


                var textfieldname = $("#<%= this.txtcarton.ClientID %>");
                DropdownFunction(textfieldname);
                $('#<%=this.txtcarton.ClientID%>').autocomplete({

                source: function (request, response) {
                    $.ajax({
                        url: '<%=ResolveUrl("~/mWebServices/FalconWebService.asmx/GetContainers") %>',
                        data: "{'Prefix': '" + request.term + "'}",
                        dataType: "json",
                        type: "POST",
                        async: true,
                        contentType: "application/json; charset=utf-8",
                        success: function (data) {
                        response($.map(data.d, function (item) {
                            return {

                                    label: item.split(',')[0],
                                    val: item.split(',')[1]
                                }

                            }))
                        }

                    });
                },
                select: function (e, i) {
                 
                },
                minLength: 0,
                    select: function (e, i) {
                        $.ajax({
                            url: '<%=ResolveUrl("~/mWebServices/FalconWebService.asmx/CheckContainerMapping") %>',
                        data: "{'Prefix': '" + i.item.val + "','Carton':'" + i.item.value+ "'}",
                        dataType: "json",
                        type: "POST",
                        async: true,
                        contentType: "application/json; charset=utf-8",
                        success: function (response) {
                            $('.FormLabels.last').css("display", "" + response.d + "");
                        }
                        })
                        $("#<%=hdncarton.ClientID %>").val(i.item.val);
                        
            }
        });
      
 
                $('#<%=chkDisc.ClientID%>').change(function () {
                    var IsQuarantine = 0;
                    var Damchecked = document.getElementById("<%=this.chkIsDamag.ClientID%>").checked;
                 var Dischecked = document.getElementById("<%=this.chkDisc.ClientID%>").checked;

                document.getElementById("<%=this.txtLocation.ClientID%>").value = "";

                if (Damchecked || Dischecked)
                    $("#<%=hifIsQuarantine.ClientID %>").val('1');

                 else if (!Dischecked && !Damchecked)
                     $("#<%=hifIsQuarantine.ClientID %>").val('0');

            });

         $('#<%=chkIsDamag.ClientID%>').change(function () {
                    var IsQuarantine = 0;
                    var Damchecked = document.getElementById("<%=this.chkIsDamag.ClientID%>").checked;
                 var Dischecked = document.getElementById("<%=this.chkDisc.ClientID%>").checked;

                document.getElementById("<%=this.txtLocation.ClientID%>").value = "";

                if (Damchecked || Dischecked)
                    $("#<%=hifIsQuarantine.ClientID %>").val('1');

                 else if (!Dischecked && !Damchecked)
                     $("#<%=hifIsQuarantine.ClientID %>").val('0');

            });
            }

            $("#divSplitmaterial").dialog({
                autoOpen: false,
                modal: true,
                minHeight: 50,
                minWidth: 300,
                height: 400,
                width: 550,
                resizable: false,
                draggable: false,
                position: ["center top", 40],
                close: function () {
                    $("#divSplitmaterial").fadeOut(500);
                    $(document).unbind('scroll');
                    $('body').css({ 'overflow': 'visible' });
                },

                //position: 'center',
                open: function (event, ui) {
               
                    $("#divSplitmaterial").hide().fadeIn(500);

                    $('body').css({ 'overflow': 'hidden' });

                    $('body').width($('body').width());

                    $(document).bind('scroll', function () {
                        window.scrollTo(0, 0);
                    });

                    $(this).parent().appendTo("#disputeDivSplitmaterial");
                }




            });
        });
       
        function closeDialog() {
            //Could cause an infinite loop because of "on close handling"
            $("#divSplitmaterial").dialog('close');
        }

        function openDialog(GoodsMovementID) {
            // alert("from");
           // BuildDialogBox(GoodsMovementID)
            $("#divSplitmaterial").dialog("option", "title", "Split Inbound Activity");
            $("#divSplitmaterial").dialog('open');
            //return false;

            NProgress.start();

            blockDialog();
            
        }

        function blockDialog() {

            //block it to clean out the data
            $("#divSplitmaterial").block({
                message: '<img src="<%=ResolveUrl("~") %>Images/async_inv.gif" />',
                css: { border: '0px' },
                fadeIn: 0,
                fadeOut: 0,
                overlayCSS: { backgroundColor: '#ffffff', opacity: 1 }
            });

            unblockDialog();
        }
         function unblockDialog() {
             $("#divSplitmaterial").unblock();

             NProgress.done();

         }

         function BuildDialogBox(GoodsMovementID) {
            // var map = new Object();
            // BuildTextBox(map);
                     $.ajax({
                         url: '<%=ResolveUrl("~/mWebServices/FalconWebService.asmx/BuildDialogbasedonMaterial") %>',
                         data: "{ 'GoodsMovementID':' " + GoodsMovementID + "','MaterialId': '" + '<%=  MRLWMSC21Common.CommonLogic.QueryString("mmid") %>' + "','GoodsMovementType':'" + '<%=MRLWMSC21Common.CommonLogic.QueryString("TransactionType")%>' + "'}",
                        dataType: "json",
                        type: "POST",
                        contentType: "application/json; charset=utf-8",
                        success: function (data) {

                            //alert(data.d);
                            var map = new Object();
                            var TotalData = data.d.toString();
                           // alert("data is"+TotalData);
                            var textitems = TotalData.split('|');
                           // alert(textitems);
                            for (position = 0; position < textitems.length; position++) {
                                var item = textitems[position].split(',');
                               // alert(item);
                               // alert(item[0]);
                                map[item[0]] = item[1];
                            }
                           // alert(map);
                            BuildTextBox(map);
                        }
                    });
               

         }
        function BuildTextBox(map) {
            //alert('map["TUoM"]');
            //alert(map["TUoM"]);
            var txtinvUom = document.getElementById('spInvUoMQty');
            txtinvUom.innerText = map["TUoM"] + "/" + map["TUoMQty"];
            //alert(map["TUoM"]);
            var hidGoodsMovement = document.getgvLightSteelBlueNewElementById('<%=hifGoodsMovementDetailsID.ClientID%>');
           // alert(hidGoodsMovement);
            hidGoodsMovement.value=map["GoodsMovementDetailsID"];
            //alert(hidGoodsMovement.value);
            //var txtatckitid = document.getElementById('<=atckitid.ClientID%>');
           // txtatckitid.value = map["KitPlannerID"];
            var txtLocation = document.getElementById('<%=txtLocation.ClientID%>');
            txtLocation.value = map["Location"];
            var chkIsDamag = document.getElementById('<%=chkIsDamag.ClientID%>');
            if (map["IsDamaged"] == "1")
                chkIsDamag.checked = true;
            var chkDisc = document.getElementById('<%=chkDisc.ClientID%>');
            if (map["HasDiscrepancy"] == "1")
                chkDisc.checked = true;

            var mspTable = document.getElementById('<%=tbsplitmaterial.ClientID%>')
           // alert(mspTable.children[0].children[0].nodeName);
            var count = mspTable.children[0].childElementCount;
           // alert(count);
            for (rowposition = 0; rowposition < count ; rowposition++) {
                var tableRow = mspTable.children[0].children[rowposition];
                //alert(tableRow.children[0].childElementCount);

               for (cellposition = 0; cellposition < tableRow.childElementCount; cellposition++) {
                   var tablecell = tableRow.children[cellposition];
                  // alert('sss' + tablecell);
                   var item = tablecell.childNodes[2];
                   var name = tablecell.innerText.split(':')[0];
                  // alert(name);
                   try {
                       if (item.nodeName == "INPUT") {
                          // alert(item.nodeName);
                           item.value = map[name];

                       }
                           
                       else if (item.nodeName == "SELECT") {
                          // alert(item.nodeName);
                           item.value = map[name];
                       }
                           
                   } catch (err) {
                   }
                  // item.value = "jjjjj";

               }
            }


        }

  </script>

    <script>
        $(document).ready(function () {
        $("#divCustomerDetails").dialog({
            autoOpen: false,
            modal: true,
            minHeight: 50,
            minWidth: 400,
            height: 480,
            width: 800,
            resizable: false,
            draggable: false,
            position: ["center top", 40],
            close: function () {
                $("#divCustomerDetails").fadeOut(500);
                $(document).unbind('scroll');
                $('body').css({ 'overflow': 'visible' });
            },

            //position: 'center',
            open: function (event, ui) {
               
                $("#divCustomerDetails").hide().fadeIn(500);

                $('body').css({ 'overflow': 'hidden' });

                $('body').width($('body').width());

                $(document).bind('scroll', function () {
                    window.scrollTo(0, 0);
                });

                $(this).parent().appendTo("#disputeCustomerDetails");
            }




        });
        });
       
        function closeCustomerDetailsDialog() {
            //Could cause an infinite loop because of "on close handling"
            $("#divCustomerDetails").dialog('close');
        }

        function openCustomerDetailsDialog() {
            // alert("from");
            // BuildDialogBox(GoodsMovementID)
            $("#divCustomerDetails").dialog("option", "title", "Material Consumption Details");
            $("#divCustomerDetails").dialog('open');
            
            NProgress.start();

            blockCusDialog();
        }

        function blockCusDialog() {

            //block it to clean out the data
            $("#divCustomerDetails").block({
                message: '<img src="<%=ResolveUrl("~") %>Images/async_inv.gif" />',
                css: { border: '0px' },
                fadeIn: 0,
                fadeOut: 0,
                overlayCSS: { backgroundColor: '#ffffff', opacity: 1 }
            });
        }

        function unblockCusDialog() {
            $("#divCustomerDetails").unblock();
            NProgress.done();
        }

        function CheckSplitQty() {
            //var textBox = document.getElementById('<=this.txtSplitQty.ClientID%>');
            //if (textBox.value == '')
            //    return;
            //var MUoMQty = parseFloat(document.getElementById('<=this.hifMuomQty.ClientID%>').value) * 100;
            //var ReceiveQty = parseFloat(document.getElementById('<=this.hifConversion.ClientID%>').value) * parseFloat(textBox.value) * 100;

            //var BUoMQty = parseFloat(document.getElementById('<=this.hifBUoMQty.ClientID%>').value) * 100;

            //if (ReceiveQty < MUoMQty) {
            //    showStickyToast(true, "'Split Qty.' should be greater than or equal to MUoM/Qty.");
            //    textBox.value = "";
            //    return;
            //}

            //if ((ReceiveQty % BUoMQty) != 0) {
            //    showStickyToast(true, "'Split Qty.' should be multiple of BUoM/Qty.");
            //    textBox.value = "";
            //    return;
            //}
            var textBox = document.getElementById('<%=this.txtSplitQty.ClientID%>');
            if (textBox.value == '')
                   return;
            //if (document.getElementById('<=this.hifMeasurementType.ClientID%>').value == "0") {
                 
            //     var ReceivedQty = parseFloat(document.getElementById('<=this.hifConversion.ClientID%>').value) * parseFloat(textBox.value) * 100;
            //     MUoMConversionvalue = parseFloat(document.getElementById('<=this.hifconversionInMUoM.ClientID%>').value) * 100;


            //     if (ReceivedQty < MUoMConversionvalue) {
            //         showStickyToast(true, "'Split Qty.' should be greater than or equal to MUoM/Qty.");
            //         textBox.value = "";
            //         return;
            //     }
            //     if ((ReceivedQty % 100) != 0) {
            //         showStickyToast(true, "'Split Qty.' should be multiple of BUoM/Qty.");
            //         textBox.value = "";
            //         return;
            //     }
            // }
            // else {
                 



                 //var ConversionvalueInMUoM = parseFloat(document.getElementById('<=this.hifconversionInMUoM.ClientID%>').value);
                 //var Quantity = parseFloat(textBox.value);
                 //var ReceivedQtyInMUoM = parseInt(ConversionvalueInMUoM * Quantity * 1000);
                 // var ModuloValue = ReceivedQtyInMUoM % 1000;
                
                 //if (ModuloValue != 0 && (Math.abs(1000 - ModuloValue)) > 100) {
                 //    showStickyToast(true, "'Split Qty.' should be multiple of MUoM Qty. <br/> Suggested Quantity is " + parseInt(Math.ceil(ReceivedQtyInMUoM / 1000) / ConversionvalueInMUoM * 1000) / 1000);
                 //    textBox.value = "";
                 //    return;
                 //}



               
             //}

            CheckDecimal(textBox);
           
        }

    </script>
    <div class="container">
    <div id="disputeDivSplitmaterial" class="">
    <div id="divSplitmaterial"  >
        <asp:UpdatePanel ChildrenAsTriggers="true" ID="upnlParentSplitDialog" runat="server" UpdateMode="Always">
                <ContentTemplate>

                    <div class="ui-dailog-body" style="height: 445px; padding-left: 10px; padding-right: 10px;">

                        <table>
                                <tr>
                                <td class="RedLabel" colspan="2"><span style="font-size: medium; color: red;">Note:</span> <span style="font-size: small; color: #ff9999;">This split is based on currently available quantity.Hence make sure you have split quantity less than the available quantity with all the specified parameters before spliting.</span>
                                    <br />
                                    <br />
                                </td>
                            </tr>
                            <tr>
                                <td colspan="2">
                                    <asp:Label ID="lblStatus_split" runat="server" CssClass="errorMsg" />
                                </td>
                            </tr>
                            <tr>
                                <td><br />
                                    <div class="flex__">
                                        <strong>BUoM/Qty.:</strong>&nbsp;&nbsp;&nbsp;&nbsp;
                                        <asp:Literal ID="ltBuomqty" runat="server"></asp:Literal>
                                    </div>
                                </td>
                                <td><br />
                                    <div class="flex__">
                                        <strong>MUoM/Qty.:</strong>&nbsp;&nbsp;&nbsp;&nbsp;
                                        <div><asp:Literal ID="ltMuomqty" runat="server" />
                                        <asp:HiddenField ID="hifMuomQty" runat="server" />
                                        <asp:HiddenField ID="hifConversion" runat="server" />
                                        <asp:HiddenField ID="hifBUoMQty" runat="server" />
                                        <asp:HiddenField ID="hifMeasurementType" runat="server" Value="0"/>
                                        <asp:HiddenField ID="hifconversionInMUoM" runat="server" />
                                        <asp:HiddenField runat="server" ID="hifIsQuarantine" Value="0" /></div>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td width="50%"><br />
                                    <div class="flex__"><strong><asp:Label ID="lbInvUoMQty" runat="server" Text="Inv. UoM/Qty.:" /></strong>&nbsp;&nbsp;&nbsp;&nbsp;
                                    <div><asp:Literal runat="server" ID="ltInvUoMQty"></asp:Literal>
                                    <asp:HiddenField ID="hifGoodsMovementDetailsID" runat="server" /></div></div>
                                </td>
                                <td><br />
                                    <div class="flex">
                                        
                                        <asp:RequiredFieldValidator ID="rfvSplitQty" runat="server" ValidationGroup="splitQuantity" ControlToValidate="txtSplitQty" Display="Dynamic" ErrorMessage=" * " />
                                        <asp:TextBox ID="txtSplitQty" onKeyPress="return checkDec(this,event)" onblur="CheckSplitQty();" runat="server" Width="120" required="required" />
                                        <label><asp:Literal ID="ltSplitQty" runat="server" Text="Split Qty." /></label>
                                        <asp:HiddenField ID="hifTotalQty" runat="server" />
                                    </div>
                                </td>

                            </tr>
                            <tr>
                                <td colspan="2">
                                    <table width="100%" id="tbsplitmaterial" runat="server" border="0">
                                    </table>
                                </td>
                            </tr>
                            <tr>
                                <td><br />
                                    <div class="flex">
                                      <asp:TextBox ID="txtcarton" SkinID="txt_Auto" runat="server" required="required" />
                                      <label><asp:Literal ID="ltcarton" runat="server" Text="Container" /></label>
                                      <asp:HiddenField ID="hdncarton" runat="server" />
                                      <asp:HiddenField ID="hiffromcartonID" runat="server" />
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                  <td class="FormLabels last" style="display:none">
                                    <asp:RequiredFieldValidator ID="rfdLocation" runat="server" ValidationGroup="splitQuantity" ControlToValidate="txtLocation" Display="Dynamic" ErrorMessage=" * " />
                                    <asp:Literal ID="ltLocation" runat="server" Text="Location:" />          
                                    <asp:TextBox ID="txtLocation" onKeypress="return checkSpecialChar(event)" SkinID="txt_Auto" runat="server" Width="100" />
                                </td>
                            </tr>
                           
                            <tr>
                                <td></td>
                                
                                <td colspan="1" align="LEFT">
                                    <asp:CheckBox ID="chkIsDamag" runat="server" Text="Is Damaged" /><br />
                                    <asp:CheckBox ID="chkDisc" runat="server" Text="Has Discrepancy" /><!--&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-->
                                    <br />
                                    <asp:CheckBox ID="chkisNonconformity" runat="server" Text="Is Non-Conformity" />
                                    <br />
                                    <%--<asp:CheckBox ID="chkAsIs" Enabled="false" runat="server" Text="As Is" />--%>
                                </td>

                            </tr>
                            <tr><td></td></tr>
                             <tr>
                                <td>
                                    <asp:Literal ID="ltKitID" runat="server" Text="Kit ID:" /><br />
                                    <asp:Label ID="lbkitid" runat="server" />
                                </td>
                                
                              
                                  

                            </tr>
                            <tr>
                                <td>&nbsp;
                                </td>
                            </tr>

                        </table>

                    </div>

                        <div class="ui-dailog-footer">
                        <div style="padding: 15px 13px 15px 5px;">
                            <asp:LinkButton ID="lnkclear"  OnClientClick="closeDialog()" runat="server"  CssClass="btn btn-primary" > Close <%= MRLWMSC21Common.CommonLogic.btnfaClear %> </asp:LinkButton>   &nbsp;&nbsp;
                            <asp:LinkButton ID="lnkSplit" OnClick="lnkSplit_Click" OnClientClick="CheckSplitQty(); showAsynchronus();" runat="server" CssClass="btn btn-primary" >Split <%= MRLWMSC21Common.CommonLogic.btnfaRightArrow %> </asp:LinkButton>                                               
                                   
                        </div>
                    </div>
                    
                </ContentTemplate>
            </asp:UpdatePanel>
        </div>
    </div>
    
    <asp:UpdatePanel ChildrenAsTriggers="true" ID="upnlParentSplitMaterial" runat="server" UpdateMode="Always">
                    <ContentTemplate>
   
                <%--<asp:Label ID="lbMaterialCode" runat="server"  Text="Material Activity Report -" Font-Size="Large" ForeColor="#6666ff" />&nbsp;
                <asp:Label ID="ltTransactionType" runat="server" Font-Size="Larger" ForeColor="#33cccc" />&nbsp;
                <asp:Label ID="lbTransactionType" runat="server" Text="-" Font-Size="Large" ForeColor="#6666ff" />&nbsp;--%>
                Part Number:<asp:Label CssClass="AutogeneratedNo" id="ltMcode" runat="server"></asp:Label>
                <%--<asp:Label ID="ltMaterialCode" runat="server" Font-Size="Larger" ForeColor="#33cccc" />--%>
                <gap5></gap5>
                        <div class="row">
                            <div class="innerScroll"> </div>
                            <asp:GridView ID="gvActiveReport" SkinID="gvLightSteelBlueNew" runat="server" Width="100%" AutoGenerateColumns="false" OnRowCommand="gvActiveReport_RowCommand" OnRowDataBound="gvActiveReport_RowDataBound" OnRowEditing="gvActiveReport_RowEditing" OnRowCancelingEdit="gvActiveReport_RowCancelingEdit" OnRowUpdating="gvActiveReport_RowUpdating">
                                <Columns>
                                    <asp:TemplateField>
                                        <ItemTemplate>
                                            <asp:Literal ID="ltTransactionNo" runat="server" Text='<%# DataBinder.Eval(Container.DataItem, "TransactionDocNo") %>' />
                                            <asp:HiddenField ID="hifTransactionDocID" runat="server" ClientIDMode="Static" Value='<%# DataBinder.Eval(Container.DataItem, "TransactionDocID") %>' />

                                        </ItemTemplate>

                                    </asp:TemplateField>
                                    <asp:TemplateField HeaderText="GRN Number">
                                        <ItemTemplate>
                                            <asp:Literal ID="ltGRNNumber" runat="server" Text='<%# DataBinder.Eval(Container.DataItem, "GRNNumber") %>' />
                                        </ItemTemplate>

                                    </asp:TemplateField>
                                    <asp:TemplateField HeaderText="POSONumber">
                                        <ItemTemplate>
                                            <asp:Literal ID="ltposoNumber" runat="server" Text='<%# DataBinder.Eval(Container.DataItem, "POSONumber") %>' />
                                        </ItemTemplate>

                                    </asp:TemplateField>

                                    <asp:TemplateField HeaderText="Storage Location">
                                        <ItemTemplate>
                                            <asp:Literal ID="ltStorageLocation" runat="server" Text='<%# DataBinder.Eval(Container.DataItem, "StorageLocation") %>' />
                                        </ItemTemplate>

                                    </asp:TemplateField>


                                    <asp:TemplateField HeaderText="Line No.">
                                        <ItemTemplate>
                                            <asp:Literal ID="ltlinenumber" runat="server" Text='<%# DataBinder.Eval(Container.DataItem, "LineNumber") %>' />
                                        </ItemTemplate>
                                    </asp:TemplateField>
                                    <asp:TemplateField HeaderText="Kit Code">
                                        <ItemTemplate>
                                            <asp:Literal ID="ltKit" runat="server" Text='<%# DataBinder.Eval(Container.DataItem, "KitPlannerID") %>' />
                                        </ItemTemplate>

                                    </asp:TemplateField>
                                    <asp:TemplateField HeaderText="BUoM/ Qty.">
                                        <ItemTemplate>
                                            <asp:Literal ID="ltBUoMQty" runat="server" Text='<%# String.Format("{0}/{1}",DataBinder.Eval(Container.DataItem, "BUoM"),DataBinder.Eval(Container.DataItem, "BUoMQty"))  %>' />
                                        </ItemTemplate>

                                    </asp:TemplateField>
                                    <asp:TemplateField HeaderText="Trans. UoM/ Qty.">
                                        <ItemTemplate>
                                            <asp:Literal ID="lttransUoM" runat="server" Text='<%#String.Format("{0}/{1}*{2}",DataBinder.Eval(Container.DataItem, "TUoM"),DataBinder.Eval(Container.DataItem, "TUoMQty"),DataBinder.Eval(Container.DataItem, "DocQty"))  %>' />
                                        </ItemTemplate>

                                    </asp:TemplateField>
                                    <%-- <asp:TemplateField HeaderStyle-Width="60" ItemStyle-HorizontalAlign="Right">
                            <ItemTemplate>
                                <asp:Literal ID="ltreceivedqty" runat="server" Text='<%# DataBinder.Eval(Container.DataItem, "TotalQty") %>' />
                            </ItemTemplate>
                           
                        </asp:TemplateField>--%>

                                    <asp:TemplateField HeaderText="Available Qty. in BUoM" ItemStyle-HorizontalAlign="Right">
                                        <ItemTemplate>
                                            <active><asp:LinkButton runat="server" ID="lnkQtyinBUoM" Font-Underline="false" Text='<%# DataBinder.Eval(Container.DataItem, "Quantity") %>' OnClientClick="openCustomerDetailsDialog()" CommandArgument='<%# DataBinder.Eval(Container.DataItem, "GoodsMovementDetailsID") %>' CommandName="CustomerDetails" />
                                <asp:Literal ID="QtyinBUoM" runat="server" Text='<%# DataBinder.Eval(Container.DataItem, "Quantity") %>'/>
                                <asp:Literal ID="ltGoodsMovementDetailsID" runat="server" Visible="false" Text='<%# DataBinder.Eval(Container.DataItem, "GoodsMovementDetailsID") %>' />
                                    <img src="../Images/redarrowright.gif">
                                </active>
                                        </ItemTemplate>
                                        <EditItemTemplate>
                                            <asp:Literal ID="QtyinBUoM" runat="server" Text='<%# DataBinder.Eval(Container.DataItem, "Quantity") %>' />
                                        </EditItemTemplate>
                                    </asp:TemplateField>
                                    <asp:TemplateField HeaderText="Has Disc.">
                                        <ItemTemplate>
                                            <asp:Image ID="imgdisc" ImageAlign="Middle" runat="server" ImageUrl='<%# Getimage(DataBinder.Eval(Container.DataItem, "HasDiscrepancy").ToString()) %>' />

                                        </ItemTemplate>

                                    </asp:TemplateField>
                                    <asp:TemplateField HeaderText="Is Dam.">
                                        <ItemTemplate>
                                            <asp:Image ID="imgDamage" ImageAlign="Middle" runat="server" ImageUrl='<%# Getimage(DataBinder.Eval(Container.DataItem, "IsDamaged").ToString()) %>' />

                                        </ItemTemplate>

                                    </asp:TemplateField>
                                    <asp:TemplateField HeaderText="QC Non Conf.">
                                        <ItemTemplate>
                                            <asp:Image ID="imgNonConf" ImageAlign="Middle" runat="server" ImageUrl='<%# Getimage(DataBinder.Eval(Container.DataItem, "IsNonConfirmity").ToString()) %>' />

                                        </ItemTemplate>

                                    </asp:TemplateField>

                                 <%--   <asp:TemplateField HeaderText="As Is">
                                        <ItemTemplate>
                                            <asp:Image ID="imgAsIs" ImageAlign="Middle" runat="server" ImageUrl='<%# Getimage(DataBinder.Eval(Container.DataItem, "AsIs").ToString()) %>' />

                                        </ItemTemplate>

                                    </asp:TemplateField>--%>
                                    <asp:TemplateField HeaderText="Location">
                                        <ItemTemplate>
                                            <asp:Literal ID="ltLocation" runat="server" Text='<%# DataBinder.Eval(Container.DataItem, "Location") %>' />
                                        </ItemTemplate>
                                        <EditItemTemplate>
                                            <asp:Literal ID="ltGoodsMovementDetailsID" runat="server" Visible="false" Text='<%# DataBinder.Eval(Container.DataItem, "GoodsMovementDetailsID") %>' />
                                            <asp:Literal ID="ltLocation" runat="server" Text='<%# DataBinder.Eval(Container.DataItem, "Location") %>' />
                                        </EditItemTemplate>
                                    </asp:TemplateField>


                                    <asp:TemplateField HeaderText="Handler">
                                        <ItemTemplate>
                                            <asp:Literal ID="ltHandler" runat="server" Text='<%# DataBinder.Eval(Container.DataItem, "CreatedBy") %>' />

                                        </ItemTemplate>

                                    </asp:TemplateField>
                                    <asp:TemplateField HeaderText="Trans. Date">
                                        <ItemTemplate>
                                            <asp:Literal ID="ltTransDate" runat="server" Text='<%# DataBinder.Eval(Container.DataItem, "CreatedOn","{0: dd-MMM-yyyy}") %>' />
                                            <br />
                                            <span title='<%# String.Format("{0} on {1}",DataBinder.Eval(Container.DataItem, "LastModifiedBy"),DataBinder.Eval(Container.DataItem, "LastModifiedOn")) %>' style="display: <%# (DataBinder.Eval(Container.DataItem, "LastModifiedBy").ToString()==""?"none":"block")%>">
                                                <img src="../Images/info.gif">
                                            </span></span>
                                        </ItemTemplate>

                                    </asp:TemplateField>


                                </Columns>
                            </asp:GridView>
                               
                        </div>
               

     </ContentTemplate>
        </asp:UpdatePanel>
       
    <div id="disputeCustomerDetails">
     <div id="divCustomerDetails"  >
         <asp:UpdatePanel ChildrenAsTriggers="true" ID="upnlCustomerDetails"  runat="server" UpdateMode="Always">
                    <ContentTemplate>

                          <div class="ui-dailog-body" style="height:375px;padding-left:10px;padding-right:10px;">

                        <table align="center">
                            <tr>
                                <td>
                                    <asp:Label ID="lbHeaderDetails" runat="server" Text="Material Consumption Details" Font-Size="Medium" ForeColor="#6666ff" />
                                    <br /><br />
                                </td>
                            </tr>

                            <tr>
                                <td height="350px" valign="top" width="680">

                                       <asp:GridView ID="gvCustomerDetails" runat="server" AutoGenerateColumns="false" SkinID="gvLightGrayNew" PageSize="10" OnPageIndexChanging="gvCustomerDetails_PageIndexChanging">
                                            <Columns>
                                                <asp:TemplateField HeaderText="OBD Number" HeaderStyle-Width="100">
                                                    <ItemTemplate>
                                                        <asp:Literal ID="ltobdnumber" runat="server" Text='<%# DataBinder.Eval(Container.DataItem, "OBDNumber") %>' />
                                                    </ItemTemplate>
                                                </asp:TemplateField>
                                                <asp:TemplateField HeaderText="SO Number" HeaderStyle-Width="100">
                                                    <ItemTemplate>
                                                        <asp:Literal ID="ltSONumber" runat="server" Text='<%# DataBinder.Eval(Container.DataItem, "SONumber") %>' />
                                                    </ItemTemplate>
                                                </asp:TemplateField>
                                                <asp:TemplateField HeaderText="Customer PO" HeaderStyle-Width="100">
                                                    <ItemTemplate>
                                                        <asp:Literal runat="server" Text='<%# DataBinder.Eval(Container.DataItem, "CustPONumber") %>' />
                                                    </ItemTemplate>
                                                </asp:TemplateField>
                                                <asp:TemplateField HeaderText="Invoice No." HeaderStyle-Width="100">
                                                    <ItemTemplate>
                                                        <asp:Literal runat="server" Text='<%# DataBinder.Eval(Container.DataItem, "InvoiceNo") %>' />
                                                    </ItemTemplate>
                                                </asp:TemplateField>
                                                <asp:TemplateField HeaderText="Customer Name" HeaderStyle-Width="100">
                                                    <ItemTemplate>
                                                        <asp:Literal ID="ltCustomerName" runat="server" Text='<%# DataBinder.Eval(Container.DataItem, "CustomerName") %>' />
                                                    </ItemTemplate>
                                                </asp:TemplateField>
                                                <asp:TemplateField HeaderText="Transaction Date" HeaderStyle-Width="100">
                                                    <ItemTemplate>
                                                        <asp:Literal ID="ltTransactionDate" runat="server" Text='<%# DataBinder.Eval(Container.DataItem, "TransactionDate","{0:dd/MM/yyyy}") %>' />
                                                    </ItemTemplate>
                                                </asp:TemplateField>
                                                <asp:TemplateField HeaderText="SUoM/ Qty." HeaderStyle-Width="100">
                                                    <ItemTemplate>
                                                        <asp:Literal ID="ltSUOM_QTY" runat="server" Text='<%#String.Format("{0}/{1}",DataBinder.Eval(Container.DataItem, "SUOM").ToString(),DataBinder.Eval(Container.DataItem, "SUOMQTY").ToString())!="/"?String.Format("{0}/{1}",DataBinder.Eval(Container.DataItem, "SUOM").ToString(),DataBinder.Eval(Container.DataItem, "SUOMQTY").ToString()):""  %>' />
                                                    </ItemTemplate>
                                                </asp:TemplateField>
                                                <asp:TemplateField HeaderText="Picked Quantity" HeaderStyle-Width="100">
                                                    <ItemTemplate>
                                                        <asp:Literal ID="ltPickedQuantity" runat="server" Text='<%#DataBinder.Eval(Container.DataItem, "PickedQuantity").ToString()  %>' />
                                                    </ItemTemplate>
                                                </asp:TemplateField>
                                            </Columns>
                                       </asp:GridView>

                                </td>
                            </tr>

                        </table>
                     
                                </div>

                         <div class="ui-dailog-footer">
                            <div style="padding: 15px 13px 15px 5px;">

                                  <asp:LinkButton ID="ltCloseCustomerDetails"  OnClientClick="closeCustomerDetailsDialog();" runat="server" CssClass="btn btn-primary" >Close <%= MRLWMSC21Common.CommonLogic.btnfaClear %></asp:LinkButton>


                                </div>
                             </div>

                        </ContentTemplate>
             </asp:UpdatePanel>
        
         </div>
        </div>           
    </div>
</asp:Content>
