//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRLWMSC21WCF.SessionValidator {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubscriptionApi.ResponseAciveSubscription", Namespace="http://schemas.datacontract.org/2004/07/ZohoServices")]
    [System.SerializableAttribute()]
    public partial class SubscriptionApiResponseAciveSubscription : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MRLWMSC21WCF.SessionValidator.SubscriptionApiSubscription[] subscriptionsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int code {
            get {
                return this.codeField;
            }
            set {
                if ((this.codeField.Equals(value) != true)) {
                    this.codeField = value;
                    this.RaisePropertyChanged("code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MRLWMSC21WCF.SessionValidator.SubscriptionApiSubscription[] subscriptions {
            get {
                return this.subscriptionsField;
            }
            set {
                if ((object.ReferenceEquals(this.subscriptionsField, value) != true)) {
                    this.subscriptionsField = value;
                    this.RaisePropertyChanged("subscriptions");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubscriptionApi.Subscription", Namespace="http://schemas.datacontract.org/2004/07/ZohoServices")]
    [System.SerializableAttribute()]
    public partial class SubscriptionApiSubscription : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string activated_atField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string current_term_ends_atField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string current_term_starts_atField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MRLWMSC21WCF.SessionValidator.SubscriptionApiCustomer customerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string expires_atField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string last_billing_atField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string next_billing_atField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string subscription_idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string activated_at {
            get {
                return this.activated_atField;
            }
            set {
                if ((object.ReferenceEquals(this.activated_atField, value) != true)) {
                    this.activated_atField = value;
                    this.RaisePropertyChanged("activated_at");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string current_term_ends_at {
            get {
                return this.current_term_ends_atField;
            }
            set {
                if ((object.ReferenceEquals(this.current_term_ends_atField, value) != true)) {
                    this.current_term_ends_atField = value;
                    this.RaisePropertyChanged("current_term_ends_at");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string current_term_starts_at {
            get {
                return this.current_term_starts_atField;
            }
            set {
                if ((object.ReferenceEquals(this.current_term_starts_atField, value) != true)) {
                    this.current_term_starts_atField = value;
                    this.RaisePropertyChanged("current_term_starts_at");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MRLWMSC21WCF.SessionValidator.SubscriptionApiCustomer customer {
            get {
                return this.customerField;
            }
            set {
                if ((object.ReferenceEquals(this.customerField, value) != true)) {
                    this.customerField = value;
                    this.RaisePropertyChanged("customer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string expires_at {
            get {
                return this.expires_atField;
            }
            set {
                if ((object.ReferenceEquals(this.expires_atField, value) != true)) {
                    this.expires_atField = value;
                    this.RaisePropertyChanged("expires_at");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string last_billing_at {
            get {
                return this.last_billing_atField;
            }
            set {
                if ((object.ReferenceEquals(this.last_billing_atField, value) != true)) {
                    this.last_billing_atField = value;
                    this.RaisePropertyChanged("last_billing_at");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string next_billing_at {
            get {
                return this.next_billing_atField;
            }
            set {
                if ((object.ReferenceEquals(this.next_billing_atField, value) != true)) {
                    this.next_billing_atField = value;
                    this.RaisePropertyChanged("next_billing_at");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string status {
            get {
                return this.statusField;
            }
            set {
                if ((object.ReferenceEquals(this.statusField, value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string subscription_id {
            get {
                return this.subscription_idField;
            }
            set {
                if ((object.ReferenceEquals(this.subscription_idField, value) != true)) {
                    this.subscription_idField = value;
                    this.RaisePropertyChanged("subscription_id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubscriptionApi.Customer", Namespace="http://schemas.datacontract.org/2004/07/ZohoServices")]
    [System.SerializableAttribute()]
    public partial class SubscriptionApiCustomer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double balanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string company_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string created_timeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string currency_codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string currency_symbolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string customer_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string display_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string first_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string last_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double outstandingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string phoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double unused_creditsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string updated_timeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double balance {
            get {
                return this.balanceField;
            }
            set {
                if ((this.balanceField.Equals(value) != true)) {
                    this.balanceField = value;
                    this.RaisePropertyChanged("balance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string company_name {
            get {
                return this.company_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.company_nameField, value) != true)) {
                    this.company_nameField = value;
                    this.RaisePropertyChanged("company_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string created_time {
            get {
                return this.created_timeField;
            }
            set {
                if ((object.ReferenceEquals(this.created_timeField, value) != true)) {
                    this.created_timeField = value;
                    this.RaisePropertyChanged("created_time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string currency_code {
            get {
                return this.currency_codeField;
            }
            set {
                if ((object.ReferenceEquals(this.currency_codeField, value) != true)) {
                    this.currency_codeField = value;
                    this.RaisePropertyChanged("currency_code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string currency_symbol {
            get {
                return this.currency_symbolField;
            }
            set {
                if ((object.ReferenceEquals(this.currency_symbolField, value) != true)) {
                    this.currency_symbolField = value;
                    this.RaisePropertyChanged("currency_symbol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string customer_id {
            get {
                return this.customer_idField;
            }
            set {
                if ((object.ReferenceEquals(this.customer_idField, value) != true)) {
                    this.customer_idField = value;
                    this.RaisePropertyChanged("customer_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string display_name {
            get {
                return this.display_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.display_nameField, value) != true)) {
                    this.display_nameField = value;
                    this.RaisePropertyChanged("display_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string first_name {
            get {
                return this.first_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.first_nameField, value) != true)) {
                    this.first_nameField = value;
                    this.RaisePropertyChanged("first_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string last_name {
            get {
                return this.last_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.last_nameField, value) != true)) {
                    this.last_nameField = value;
                    this.RaisePropertyChanged("last_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mobile {
            get {
                return this.mobileField;
            }
            set {
                if ((object.ReferenceEquals(this.mobileField, value) != true)) {
                    this.mobileField = value;
                    this.RaisePropertyChanged("mobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double outstanding {
            get {
                return this.outstandingField;
            }
            set {
                if ((this.outstandingField.Equals(value) != true)) {
                    this.outstandingField = value;
                    this.RaisePropertyChanged("outstanding");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                if ((object.ReferenceEquals(this.phoneField, value) != true)) {
                    this.phoneField = value;
                    this.RaisePropertyChanged("phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string status {
            get {
                return this.statusField;
            }
            set {
                if ((object.ReferenceEquals(this.statusField, value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double unused_credits {
            get {
                return this.unused_creditsField;
            }
            set {
                if ((this.unused_creditsField.Equals(value) != true)) {
                    this.unused_creditsField = value;
                    this.RaisePropertyChanged("unused_credits");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string updated_time {
            get {
                return this.updated_timeField;
            }
            set {
                if ((object.ReferenceEquals(this.updated_timeField, value) != true)) {
                    this.updated_timeField = value;
                    this.RaisePropertyChanged("updated_time");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubscriptionApi.ResponseAllPlan", Namespace="http://schemas.datacontract.org/2004/07/ZohoServices")]
    [System.SerializableAttribute()]
    public partial class SubscriptionApiResponseAllPlan : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MRLWMSC21WCF.SessionValidator.SubscriptionApiPlan[] PlansField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MRLWMSC21WCF.SessionValidator.SubscriptionApiPlan[] Plans {
            get {
                return this.PlansField;
            }
            set {
                if ((object.ReferenceEquals(this.PlansField, value) != true)) {
                    this.PlansField = value;
                    this.RaisePropertyChanged("Plans");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int code {
            get {
                return this.codeField;
            }
            set {
                if ((this.codeField.Equals(value) != true)) {
                    this.codeField = value;
                    this.RaisePropertyChanged("code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubscriptionApi.Plan", Namespace="http://schemas.datacontract.org/2004/07/ZohoServices")]
    [System.SerializableAttribute()]
    public partial class SubscriptionApiPlan : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int billing_cyclesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string created_timeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int intervalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string interval_unitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool is_taxableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MRLWMSC21WCF.SessionValidator.SubscriptionApiitem_tax_preferences objitem_tax_preferencesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string plan_codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string product_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int recurring_priceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int setup_feeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tax_exemption_codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tax_exemption_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tax_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int trial_periodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string updated_timeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int billing_cycles {
            get {
                return this.billing_cyclesField;
            }
            set {
                if ((this.billing_cyclesField.Equals(value) != true)) {
                    this.billing_cyclesField = value;
                    this.RaisePropertyChanged("billing_cycles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string created_time {
            get {
                return this.created_timeField;
            }
            set {
                if ((object.ReferenceEquals(this.created_timeField, value) != true)) {
                    this.created_timeField = value;
                    this.RaisePropertyChanged("created_time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int interval {
            get {
                return this.intervalField;
            }
            set {
                if ((this.intervalField.Equals(value) != true)) {
                    this.intervalField = value;
                    this.RaisePropertyChanged("interval");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string interval_unit {
            get {
                return this.interval_unitField;
            }
            set {
                if ((object.ReferenceEquals(this.interval_unitField, value) != true)) {
                    this.interval_unitField = value;
                    this.RaisePropertyChanged("interval_unit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool is_taxable {
            get {
                return this.is_taxableField;
            }
            set {
                if ((this.is_taxableField.Equals(value) != true)) {
                    this.is_taxableField = value;
                    this.RaisePropertyChanged("is_taxable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MRLWMSC21WCF.SessionValidator.SubscriptionApiitem_tax_preferences objitem_tax_preferences {
            get {
                return this.objitem_tax_preferencesField;
            }
            set {
                if ((object.ReferenceEquals(this.objitem_tax_preferencesField, value) != true)) {
                    this.objitem_tax_preferencesField = value;
                    this.RaisePropertyChanged("objitem_tax_preferences");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string plan_code {
            get {
                return this.plan_codeField;
            }
            set {
                if ((object.ReferenceEquals(this.plan_codeField, value) != true)) {
                    this.plan_codeField = value;
                    this.RaisePropertyChanged("plan_code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string product_id {
            get {
                return this.product_idField;
            }
            set {
                if ((object.ReferenceEquals(this.product_idField, value) != true)) {
                    this.product_idField = value;
                    this.RaisePropertyChanged("product_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int recurring_price {
            get {
                return this.recurring_priceField;
            }
            set {
                if ((this.recurring_priceField.Equals(value) != true)) {
                    this.recurring_priceField = value;
                    this.RaisePropertyChanged("recurring_price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int setup_fee {
            get {
                return this.setup_feeField;
            }
            set {
                if ((this.setup_feeField.Equals(value) != true)) {
                    this.setup_feeField = value;
                    this.RaisePropertyChanged("setup_fee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string status {
            get {
                return this.statusField;
            }
            set {
                if ((object.ReferenceEquals(this.statusField, value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tax_exemption_code {
            get {
                return this.tax_exemption_codeField;
            }
            set {
                if ((object.ReferenceEquals(this.tax_exemption_codeField, value) != true)) {
                    this.tax_exemption_codeField = value;
                    this.RaisePropertyChanged("tax_exemption_code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tax_exemption_id {
            get {
                return this.tax_exemption_idField;
            }
            set {
                if ((object.ReferenceEquals(this.tax_exemption_idField, value) != true)) {
                    this.tax_exemption_idField = value;
                    this.RaisePropertyChanged("tax_exemption_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tax_id {
            get {
                return this.tax_idField;
            }
            set {
                if ((object.ReferenceEquals(this.tax_idField, value) != true)) {
                    this.tax_idField = value;
                    this.RaisePropertyChanged("tax_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int trial_period {
            get {
                return this.trial_periodField;
            }
            set {
                if ((this.trial_periodField.Equals(value) != true)) {
                    this.trial_periodField = value;
                    this.RaisePropertyChanged("trial_period");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string updated_time {
            get {
                return this.updated_timeField;
            }
            set {
                if ((object.ReferenceEquals(this.updated_timeField, value) != true)) {
                    this.updated_timeField = value;
                    this.RaisePropertyChanged("updated_time");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubscriptionApi.item_tax_preferences", Namespace="http://schemas.datacontract.org/2004/07/ZohoServices")]
    [System.SerializableAttribute()]
    public partial class SubscriptionApiitem_tax_preferences : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tax_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tax_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tax_percentageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tax_specificationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tax_id {
            get {
                return this.tax_idField;
            }
            set {
                if ((object.ReferenceEquals(this.tax_idField, value) != true)) {
                    this.tax_idField = value;
                    this.RaisePropertyChanged("tax_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tax_name {
            get {
                return this.tax_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.tax_nameField, value) != true)) {
                    this.tax_nameField = value;
                    this.RaisePropertyChanged("tax_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tax_percentage {
            get {
                return this.tax_percentageField;
            }
            set {
                if ((object.ReferenceEquals(this.tax_percentageField, value) != true)) {
                    this.tax_percentageField = value;
                    this.RaisePropertyChanged("tax_percentage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tax_specification {
            get {
                return this.tax_specificationField;
            }
            set {
                if ((object.ReferenceEquals(this.tax_specificationField, value) != true)) {
                    this.tax_specificationField = value;
                    this.RaisePropertyChanged("tax_specification");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SessionValidator.ISingleSignOnDBSink")]
    public interface ISingleSignOnDBSink {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISingleSignOnDBSink/InsertWMS", ReplyAction="http://tempuri.org/ISingleSignOnDBSink/InsertWMSResponse")]
        string InsertWMS(string Json, string SSOUserID, string SSOAccountID, string Password, string EncPwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISingleSignOnDBSink/InsertWMS", ReplyAction="http://tempuri.org/ISingleSignOnDBSink/InsertWMSResponse")]
        System.Threading.Tasks.Task<string> InsertWMSAsync(string Json, string SSOUserID, string SSOAccountID, string Password, string EncPwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISingleSignOnDBSink/InsertInvSSO", ReplyAction="http://tempuri.org/ISingleSignOnDBSink/InsertInvSSOResponse")]
        string InsertInvSSO(string Account, string ZohoID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISingleSignOnDBSink/InsertInvSSO", ReplyAction="http://tempuri.org/ISingleSignOnDBSink/InsertInvSSOResponse")]
        System.Threading.Tasks.Task<string> InsertInvSSOAsync(string Account, string ZohoID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISingleSignOnDBSink/InsertUserInvSSO", ReplyAction="http://tempuri.org/ISingleSignOnDBSink/InsertUserInvSSOResponse")]
        string InsertUserInvSSO(string User, string UserID, string EncPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISingleSignOnDBSink/InsertUserInvSSO", ReplyAction="http://tempuri.org/ISingleSignOnDBSink/InsertUserInvSSOResponse")]
        System.Threading.Tasks.Task<string> InsertUserInvSSOAsync(string User, string UserID, string EncPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISingleSignOnDBSink/InsertSubscriptionInvSSO", ReplyAction="http://tempuri.org/ISingleSignOnDBSink/InsertSubscriptionInvSSOResponse")]
        string InsertSubscriptionInvSSO(string Subscription, string SubscriptionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISingleSignOnDBSink/InsertSubscriptionInvSSO", ReplyAction="http://tempuri.org/ISingleSignOnDBSink/InsertSubscriptionInvSSOResponse")]
        System.Threading.Tasks.Task<string> InsertSubscriptionInvSSOAsync(string Subscription, string SubscriptionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISingleSignOnDBSink/ValidateUserLogin", ReplyAction="http://tempuri.org/ISingleSignOnDBSink/ValidateUserLoginResponse")]
        string ValidateUserLogin(string User);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISingleSignOnDBSink/ValidateUserLogin", ReplyAction="http://tempuri.org/ISingleSignOnDBSink/ValidateUserLoginResponse")]
        System.Threading.Tasks.Task<string> ValidateUserLoginAsync(string User);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISingleSignOnDBSink/EndUserSession", ReplyAction="http://tempuri.org/ISingleSignOnDBSink/EndUserSessionResponse")]
        void EndUserSession(string ClientID, string SessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISingleSignOnDBSink/EndUserSession", ReplyAction="http://tempuri.org/ISingleSignOnDBSink/EndUserSessionResponse")]
        System.Threading.Tasks.Task EndUserSessionAsync(string ClientID, string SessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISingleSignOnDBSink/ValidateUserSession", ReplyAction="http://tempuri.org/ISingleSignOnDBSink/ValidateUserSessionResponse")]
        int ValidateUserSession(string User);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISingleSignOnDBSink/ValidateUserSession", ReplyAction="http://tempuri.org/ISingleSignOnDBSink/ValidateUserSessionResponse")]
        System.Threading.Tasks.Task<int> ValidateUserSessionAsync(string User);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISingleSignOnDBSink/GetAllSubscriptions", ReplyAction="http://tempuri.org/ISingleSignOnDBSink/GetAllSubscriptionsResponse")]
        MRLWMSC21WCF.SessionValidator.SubscriptionApiResponseAciveSubscription GetAllSubscriptions();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISingleSignOnDBSink/GetAllSubscriptions", ReplyAction="http://tempuri.org/ISingleSignOnDBSink/GetAllSubscriptionsResponse")]
        System.Threading.Tasks.Task<MRLWMSC21WCF.SessionValidator.SubscriptionApiResponseAciveSubscription> GetAllSubscriptionsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISingleSignOnDBSink/GetAllPlans", ReplyAction="http://tempuri.org/ISingleSignOnDBSink/GetAllPlansResponse")]
        MRLWMSC21WCF.SessionValidator.SubscriptionApiResponseAllPlan GetAllPlans();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISingleSignOnDBSink/GetAllPlans", ReplyAction="http://tempuri.org/ISingleSignOnDBSink/GetAllPlansResponse")]
        System.Threading.Tasks.Task<MRLWMSC21WCF.SessionValidator.SubscriptionApiResponseAllPlan> GetAllPlansAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISingleSignOnDBSink/InsertUserInvWMS", ReplyAction="http://tempuri.org/ISingleSignOnDBSink/InsertUserInvWMSResponse")]
        string InsertUserInvWMS(string User, string Account, string Tenant, string email, string SSOUserID, string firstname, string mobile, string Password, string EncPassword, string LastName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISingleSignOnDBSink/InsertUserInvWMS", ReplyAction="http://tempuri.org/ISingleSignOnDBSink/InsertUserInvWMSResponse")]
        System.Threading.Tasks.Task<string> InsertUserInvWMSAsync(string User, string Account, string Tenant, string email, string SSOUserID, string firstname, string mobile, string Password, string EncPassword, string LastName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISingleSignOnDBSink/LoginActivation", ReplyAction="http://tempuri.org/ISingleSignOnDBSink/LoginActivationResponse")]
        string LoginActivation(string AccountID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISingleSignOnDBSink/LoginActivation", ReplyAction="http://tempuri.org/ISingleSignOnDBSink/LoginActivationResponse")]
        System.Threading.Tasks.Task<string> LoginActivationAsync(string AccountID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISingleSignOnDBSink/ChangePassword", ReplyAction="http://tempuri.org/ISingleSignOnDBSink/ChangePasswordResponse")]
        string ChangePassword(string EmailID, string EncOldPassword, string EncNewPassword, string UserID, string ChangeType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISingleSignOnDBSink/ChangePassword", ReplyAction="http://tempuri.org/ISingleSignOnDBSink/ChangePasswordResponse")]
        System.Threading.Tasks.Task<string> ChangePasswordAsync(string EmailID, string EncOldPassword, string EncNewPassword, string UserID, string ChangeType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISingleSignOnDBSink/ForgetPassword", ReplyAction="http://tempuri.org/ISingleSignOnDBSink/ForgetPasswordResponse")]
        string ForgetPassword(string UserID, string EmailID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISingleSignOnDBSink/ForgetPassword", ReplyAction="http://tempuri.org/ISingleSignOnDBSink/ForgetPasswordResponse")]
        System.Threading.Tasks.Task<string> ForgetPasswordAsync(string UserID, string EmailID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISingleSignOnDBSinkChannel : MRLWMSC21WCF.SessionValidator.ISingleSignOnDBSink, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SingleSignOnDBSinkClient : System.ServiceModel.ClientBase<MRLWMSC21WCF.SessionValidator.ISingleSignOnDBSink>, MRLWMSC21WCF.SessionValidator.ISingleSignOnDBSink {
        
        public SingleSignOnDBSinkClient() {
        }
        
        public SingleSignOnDBSinkClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SingleSignOnDBSinkClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SingleSignOnDBSinkClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SingleSignOnDBSinkClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string InsertWMS(string Json, string SSOUserID, string SSOAccountID, string Password, string EncPwd) {
            return base.Channel.InsertWMS(Json, SSOUserID, SSOAccountID, Password, EncPwd);
        }
        
        public System.Threading.Tasks.Task<string> InsertWMSAsync(string Json, string SSOUserID, string SSOAccountID, string Password, string EncPwd) {
            return base.Channel.InsertWMSAsync(Json, SSOUserID, SSOAccountID, Password, EncPwd);
        }
        
        public string InsertInvSSO(string Account, string ZohoID) {
            return base.Channel.InsertInvSSO(Account, ZohoID);
        }
        
        public System.Threading.Tasks.Task<string> InsertInvSSOAsync(string Account, string ZohoID) {
            return base.Channel.InsertInvSSOAsync(Account, ZohoID);
        }
        
        public string InsertUserInvSSO(string User, string UserID, string EncPassword) {
            return base.Channel.InsertUserInvSSO(User, UserID, EncPassword);
        }
        
        public System.Threading.Tasks.Task<string> InsertUserInvSSOAsync(string User, string UserID, string EncPassword) {
            return base.Channel.InsertUserInvSSOAsync(User, UserID, EncPassword);
        }
        
        public string InsertSubscriptionInvSSO(string Subscription, string SubscriptionID) {
            return base.Channel.InsertSubscriptionInvSSO(Subscription, SubscriptionID);
        }
        
        public System.Threading.Tasks.Task<string> InsertSubscriptionInvSSOAsync(string Subscription, string SubscriptionID) {
            return base.Channel.InsertSubscriptionInvSSOAsync(Subscription, SubscriptionID);
        }
        
        public string ValidateUserLogin(string User) {
            return base.Channel.ValidateUserLogin(User);
        }
        
        public System.Threading.Tasks.Task<string> ValidateUserLoginAsync(string User) {
            return base.Channel.ValidateUserLoginAsync(User);
        }
        
        public void EndUserSession(string ClientID, string SessionID) {
            base.Channel.EndUserSession(ClientID, SessionID);
        }
        
        public System.Threading.Tasks.Task EndUserSessionAsync(string ClientID, string SessionID) {
            return base.Channel.EndUserSessionAsync(ClientID, SessionID);
        }
        
        public int ValidateUserSession(string User) {
            return base.Channel.ValidateUserSession(User);
        }
        
        public System.Threading.Tasks.Task<int> ValidateUserSessionAsync(string User) {
            return base.Channel.ValidateUserSessionAsync(User);
        }
        
        public MRLWMSC21WCF.SessionValidator.SubscriptionApiResponseAciveSubscription GetAllSubscriptions() {
            return base.Channel.GetAllSubscriptions();
        }
        
        public System.Threading.Tasks.Task<MRLWMSC21WCF.SessionValidator.SubscriptionApiResponseAciveSubscription> GetAllSubscriptionsAsync() {
            return base.Channel.GetAllSubscriptionsAsync();
        }
        
        public MRLWMSC21WCF.SessionValidator.SubscriptionApiResponseAllPlan GetAllPlans() {
            return base.Channel.GetAllPlans();
        }
        
        public System.Threading.Tasks.Task<MRLWMSC21WCF.SessionValidator.SubscriptionApiResponseAllPlan> GetAllPlansAsync() {
            return base.Channel.GetAllPlansAsync();
        }
        
        public string InsertUserInvWMS(string User, string Account, string Tenant, string email, string SSOUserID, string firstname, string mobile, string Password, string EncPassword, string LastName) {
            return base.Channel.InsertUserInvWMS(User, Account, Tenant, email, SSOUserID, firstname, mobile, Password, EncPassword, LastName);
        }
        
        public System.Threading.Tasks.Task<string> InsertUserInvWMSAsync(string User, string Account, string Tenant, string email, string SSOUserID, string firstname, string mobile, string Password, string EncPassword, string LastName) {
            return base.Channel.InsertUserInvWMSAsync(User, Account, Tenant, email, SSOUserID, firstname, mobile, Password, EncPassword, LastName);
        }
        
        public string LoginActivation(string AccountID) {
            return base.Channel.LoginActivation(AccountID);
        }
        
        public System.Threading.Tasks.Task<string> LoginActivationAsync(string AccountID) {
            return base.Channel.LoginActivationAsync(AccountID);
        }
        
        public string ChangePassword(string EmailID, string EncOldPassword, string EncNewPassword, string UserID, string ChangeType) {
            return base.Channel.ChangePassword(EmailID, EncOldPassword, EncNewPassword, UserID, ChangeType);
        }
        
        public System.Threading.Tasks.Task<string> ChangePasswordAsync(string EmailID, string EncOldPassword, string EncNewPassword, string UserID, string ChangeType) {
            return base.Channel.ChangePasswordAsync(EmailID, EncOldPassword, EncNewPassword, UserID, ChangeType);
        }
        
        public string ForgetPassword(string UserID, string EmailID) {
            return base.Channel.ForgetPassword(UserID, EmailID);
        }
        
        public System.Threading.Tasks.Task<string> ForgetPasswordAsync(string UserID, string EmailID) {
            return base.Channel.ForgetPasswordAsync(UserID, EmailID);
        }
    }
}
